### ISSUE TITLE
Crash wenn Aufgabe bearbeitet wird und auf "kann nur erledigt werden wenn.." geklickt wird

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/watnu#60]
Traceback (most recent call last):
  File "F:\Dropbox (Privat)\code\watnu\master\src\watnu\main.py", line 1062, in time_constraints_button
    dialog = Chooser(self, self.task, kind="constraints")
    return cases[kind](editor, task)
  File "F:\Dropbox (Privat)\code\watnu\master\src\watnu\main.py", line 1773, in __init__
    for column, day in enumerate(np.reshape(task.constraints, (7,144))):
  File "<__array_function__ internals>", line 5, in reshape
  File "C:\Users\micro\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (7,144)

**Comment by amogorkon** [comment]
Constraints sollten jetzt wie erwartet funktionieren.
